// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionOpenPopUp
{
    static class Vsix
    {
        public const string Id = "9ea776a6-e317-4ba8-a957-fa59958ec214";
        public const string Name = "Solution Open Pop Up";
        public const string Description = @"Display the contents of certain text files when the solution is opened in a pop-up window. A handy way to share solution-specific gotchas, non-critical team messages or your own personal notes for a solution. ";
        public const string Language = "en-US";
        public const string Version = "1.0.40";
        public const string Author = "Greg Trevellick";
        public const string Tags = "solution open, popup, pop-up, pop up, gotcha, gotchas, read me, readme, readme.txt";
    }
}
