// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionOpenPopUp
{
    static class Vsix
    {
        public const string Id = "6238ee82-12cb-4ad9-88ac-19181fde5832";
        public const string Name = "Solution Load Sample gregt2";
        public const string Description = @"Demonstrates use of solution load events";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
