// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionOpenPopUp
{
    static class Vsix
    {
        public const string Id = "9ea776a6-e317-4ba8-a957-fa59958ec214";
        public const string Name = "SolutionOpenPopUp";
        public const string Description = @"This extension will open a pop-up dialog containing the contents of a specific text file in a solution, when the solution is opened.

This [Visual Studio][VisualStudioUrl] extension will open a pop-up dialog containing 
the contents of a specific text file in a solution, when the solution is opened.

";
        public const string Language = "en-US";
        public const string Version = "1.0.8";
        public const string Author = "Greg Trevellick";
        public const string Tags = "solution open, popup, pop-up, pop up";
    }
}
