// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionOpenPopUp
{
    static class Vsix
    {
        public const string Id = "9ea776a6-e317-4ba8-a957-fa59958ec214";
        public const string Name = "Solution Open Pop Up";
        public const string Description = @"When specific text file(s) exist in a solution folder, their content is optionally shown in a pop-up dialog window, when the solution is opened.
";
        public const string Language = "en-US";
        public const string Version = "1.0.14";
        public const string Author = "Greg Trevellick";
        public const string Tags = "solution open, popup, pop-up, pop up, gotcha, gotchas";
    }
}
